-- 002_categorias.sql
-- CRUD de categorias

begin;

create table if not exists public.categorias (
  id bigint generated by default as identity primary key,
  nome text not null,
  slug text not null unique,
  descricao text,
  ativa boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categorias_nome_unico unique (nome)
);

create index if not exists categorias_ativa_idx on public.categorias (ativa);

drop trigger if exists trg_categorias_updated_at on public.categorias;
create trigger trg_categorias_updated_at
before update on public.categorias
for each row execute function public.set_updated_at();

commit;
