-- 003_produtos.sql
-- CRUD de produtos

begin;

create table if not exists public.produtos (
  id bigint generated by default as identity primary key,
  categoria_id bigint not null references public.categorias(id) on update cascade on delete restrict,
  nome text not null,
  slug text not null unique,
  descricao text,
  quantidade integer not null default 0 check (quantidade >= 0),
  preco_custo numeric(12,2) not null default 0 check (preco_custo >= 0),
  preco_venda numeric(12,2) not null default 0 check (preco_venda >= 0),
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produtos_categoria_id_idx on public.produtos (categoria_id);
create index if not exists produtos_ativo_idx on public.produtos (ativo);
create index if not exists produtos_nome_idx on public.produtos (nome);

drop trigger if exists trg_produtos_updated_at on public.produtos;
create trigger trg_produtos_updated_at
before update on public.produtos
for each row execute function public.set_updated_at();

commit;
