-- 004_produto_imagens.sql
-- Um produto pode ter 1 ou N imagens

begin;

create table if not exists public.produto_imagens (
  id bigint generated by default as identity primary key,
  produto_id bigint not null references public.produtos(id) on update cascade on delete cascade,
  url text not null,
  alt_text text,
  ordem integer not null default 0 check (ordem >= 0),
  destaque boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists produto_imagens_produto_id_idx on public.produto_imagens (produto_id);
create index if not exists produto_imagens_ordem_idx on public.produto_imagens (produto_id, ordem);

-- No maximo uma imagem destaque por produto
create unique index if not exists produto_imagens_unica_destaque_por_produto
  on public.produto_imagens (produto_id)
  where destaque = true;

drop trigger if exists trg_produto_imagens_updated_at on public.produto_imagens;
create trigger trg_produto_imagens_updated_at
before update on public.produto_imagens
for each row execute function public.set_updated_at();

commit;
