create table if not exists public.gestores (
  id bigint generated by default as identity primary key,
  nome text not null,
  sexo text not null,
  created_at timestamptz not null default now()
);

create index if not exists gestores_created_at_idx
  on public.gestores (created_at desc);


alter table public.gestores enable row level security;

create policy "gestores_select_anon"
on public.gestores
for select
to anon
using (true);

create policy "gestores_insert_anon"
on public.gestores
for insert
to anon
with check (true);
